### ISSUE TITLE
Add UI for Not Found

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#101]
- [ ] Workspace not found: Full screen, show "Workspace not found", show user button "Return to dashboard"
- [ ] Workspace Board not found: Full screen, show user button "Return to dashboard"
- [ ] Task not found: Full screen, show user button "Return to dashboard"

**Comment by nbot0902** [comment]
![1-1](https://user-images.githubusercontent.com/11695391/154638271-d572fc2d-d246-4793-8a23-e7105020c61c.png)

Isn't it this?

**Comment by nbot0902** [comment]
![1-2](https://user-images.githubusercontent.com/11695391/155108400-f7a96ba5-f52a-4cd6-9230-685a46afb7f3.png)
![1-1](https://user-images.githubusercontent.com/11695391/155108409-89abbff5-f7e4-4fc9-a2d2-64bd4431a158.png)
![1-3](https://user-images.githubusercontent.com/11695391/155108413-1c1f0718-0245-42e4-990b-b2db3285f6f4.png)
![1-4](https://user-images.githubusercontent.com/11695391/155108415-d6bc96d5-20c3-41dc-b4eb-c1ffc4e63c63.png)

Considering the implementation time and effort, I thought it would be better to use the same diagram.
You can use the same illustration if you notice a new error pattern.
