### ISSUE TITLE
Revise UI for workspace settings screen

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#112]
- There should be one global save button for picture, title and description
- There should be a cancel button to revert the changes

**Comment by nbot0902** [comment]
見た目をシンプルにしたかったので、全体的にそういう作りにしてたんですが、了解です。

**Comment by nbot0902** [comment]
![1-1](https://user-images.githubusercontent.com/11695391/155056101-3601a86c-86fb-4ef1-8f2b-e911cc708ca5.png)
![1-2](https://user-images.githubusercontent.com/11695391/155056103-2a196d31-78c3-40fc-8f64-9ab13a7bb825.png)
![1-3](https://user-images.githubusercontent.com/11695391/155056097-7243e59b-00d7-4f85-a331-ceb610a224ca.png)
