### ISSUE TITLE
Revise UI for user profile settings

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#114]
- Add edit mode that can be accessed by pressing "edit" button

**Comment by nbot0902** [comment]
Okay

**Comment by nbot0902** [comment]
![1-1](https://user-images.githubusercontent.com/11695391/155054481-5c20cf20-0922-4184-a6ca-1ee8c4ba619e.png)
![1-2](https://user-images.githubusercontent.com/11695391/155054492-0c893757-c7d0-4d86-a05c-a0e1f15fab0f.png)
![1-3](https://user-images.githubusercontent.com/11695391/155054500-0d7ce30b-67d2-43bb
![1-4](https://user-images.githubusercontent.com/11695391/155054503-dee78e44-54c8-4931-8186-d3d0fec233c3.png)
-8616-293e6f6d6535.png)
