### ISSUE TITLE
Create user profile link in user drop down in header

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#116]
There should be a link going to the user profile settings in the header drop down menu

**Comment by justuswilhelm** [comment]
<img width="257" alt="Screenshot-2022-02-23-at-15 28 13" src="https://user-images.githubusercontent.com/1641042/155271198-2a39ab5b-7ccd-4610-b174-13b3667e08a0.png">
Giosue created this temporarily

**Comment by nbot0902** [comment]
<img width="302" alt="スクリーンショット 2022-02-23 15 37 41" src="https://user-images.githubusercontent.com/11695391/155271771-65f2d5f3-1f49-41d3-8ccb-272d3aa9e7c4.png">

**Comment by justuswilhelm** [comment]
Thanks!
