### ISSUE TITLE
Review UI for adding a team member

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#47]
Right now, there is a nickname field. What is the meaning of it?

**Comment by nbot0902** [comment]
![1-4-4](https://user-images.githubusercontent.com/11695391/154186786-bd3dd3af-2215-436d-aa5e-ba6098439a11.png)

**Comment by justuswilhelm** [comment]
This is about https://www.figma.com/file/6QBQfUV5Z9jR14ZPlvNxNe/jwp-consulting?node-id=66%3A3

**Comment by nbot0902** [comment]
![1-1](https://user-images.githubusercontent.com/11695391/154210929-e6793c3b-1ee8-4874-8c8e-44ab31cd09e2.png)
