### ISSUE TITLE
Create UI for deleting workspaces

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#51]

**Comment by nbot0902** [comment]
![1-1](https://user-images.githubusercontent.com/11695391/153998841-99753614-469e-4211-935f-4092d608089a.png)
![1-2](https://user-images.githubusercontent.com/11695391/153998839-17df6d33-ca04-4b2f-a202-11d695a59215.png)
![1-3](https://user-images.githubusercontent.com/11695391/153998835-d6f7f1c4-7f27-481b-bcd6-9df9e7f6a00c.png)

**Comment by justuswilhelm** [comment]
Needs a confirmation popup

**Comment by justuswilhelm** [comment]
Thanks!
