### ISSUE TITLE
Create New workspace board and edit workspace board UI 

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#64]

**Comment by nbot0902** [comment]
![1-3-2](https://user-images.githubusercontent.com/11695391/154182532-351d95cd-df65-42a5-98a5-710466fa2468.png)
![1-3-3](https://user-images.githubusercontent.com/11695391/154182574-9e543e3d-1e4e-409d-a4a3-dafd7b71dec6.png)
