### ISSUE TITLE
Create fixed header

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#71]
Should have

- user avatar (with user menu (including logout, profile settings))
- link to landing page (just a logo)

Make it look like GitHub

**Comment by nbot0902** [comment]
![1-3-1](https://user-images.githubusercontent.com/11695391/154210099-ab57ae61-0ab0-4f27-a6a9-49df407fcbfe.png)

**Comment by justuswilhelm** [comment]
Could you add a UI sketch for the menu as well? It would be helpful to roughly know how it looks like.

**Comment by nbot0902** [comment]
![1-1-1](https://user-images.githubusercontent.com/11695391/154216587-4cdf1261-b6e2-4656-91a0-9fd457ce8c14.png)

**Comment by nbot0902** [comment]
@justuswilhelm 
Let's decide at the end what menu to add !
