### ISSUE TITLE
Create UI for setting task deadlines

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#73]

**Comment by nbot0902** [comment]
![1-1](https://user-images.githubusercontent.com/11695391/154010565-cc1ad40f-7344-4148-9eb9-3aa39716d644.png)
![1-2](https://user-images.githubusercontent.com/11695391/154010575-5a09f199-8faa-442f-a76b-247bc4ad4334.png)

**Comment by nbot0902** [comment]
![1-2](https://user-images.githubusercontent.com/11695391/154010859-8d89b550-bd8b-4e1d-97cd-f3043fed50e6.png)
![1-1](https://user-images.githubusercontent.com/11695391/154010864-20876dff-7dbe-4b86-b4d6-e52405d7189b.png)

**Comment by justuswilhelm** [comment]
Please move deadline below description

**Comment by nbot0902** [comment]
![1-2](https://user-images.githubusercontent.com/11695391/154014879-8f9c89c3-13bb-41d3-a7f3-7d83b17444bd.png)
![1-2](https://user-images.githubusercontent.com/11695391/154014965-7ae316cb-5ce7-4e8b-aced-e99aae68539e.png)
![1-1](https://user-images.githubusercontent.com/11695391/154014973-960a4dde-172e-4af3-9ce9-dd6da5d7476e.png)

**Comment by justuswilhelm** [comment]
Very good, thanks
