### ISSUE TITLE
Design UI for disconnected state

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#75]

**Comment by nbot0902** [comment]
![1-7-1](https://user-images.githubusercontent.com/11695391/154005949-610378fb-8aac-4746-a396-7b3db5f76f98.png)

**Comment by justuswilhelm** [comment]
Please move the red bar to the top like Netflix :)

**Comment by nbot0902** [comment]
![1-7-1](https://user-images.githubusercontent.com/11695391/154015151-277088c6-8bfa-4141-88a6-c2ef6c3f0891.png)
