### ISSUE TITLE
Delete Section UI Modal

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#80]
We need a confirm modal for when the user clicks on the delete button of a section

**Comment by nbot0902** [comment]
![1-4-2](https://user-images.githubusercontent.com/11695391/153995874-6ee4a4e7-523f-4648-92b8-218a98cc0438.png)
![1-4-1](https://user-images.githubusercontent.com/11695391/153995882-56b01076-8f83-402a-8c1c-aab93e5edd8b.png)
![1-4-3](https://user-images.githubusercontent.com/11695391/153995883-6986549f-dd93-45c2-b2a6-1b48042eadb6.png)

**Comment by justuswilhelm** [comment]
Good! Thanks :)
