### ISSUE TITLE
Edit Section UI

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#81]
We need a UI design for when the user wants to edit the title of a section

**Comment by nbot0902** [comment]
![1-5-1](https://user-images.githubusercontent.com/11695391/153996196-64b3a1fc-f794-4222-9c61-5914e379dfc7.png)
![1-5-2](https://user-images.githubusercontent.com/11695391/153996200-24171adb-0719-45df-a076-292cd5dd8c35.png)
