### ISSUE TITLE
Add Section UI

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#82]
We need a UI for when the user clicks on "New Section"

**Comment by nbot0902** [comment]
<img width="757" alt="スクリーンショット 2022-02-15 13 44 03" src="https://user-images.githubusercontent.com/11695391/153994095-36b8097e-89b6-40a3-a9e1-0cb444e2b61e.png">

**Comment by justuswilhelm** [comment]
The user needs to be able to enter the section's name when they click on the new section button

**Comment by nbot0902** [comment]
![1-2-2](https://user-images.githubusercontent.com/11695391/154006039-5ab7ce3c-4417-41ef-84f5-f02813182864.png)
![1-2-1](https://user-images.githubusercontent.com/11695391/154006046-2957013a-9049-4da8-8b38-663806e02315.png)
