### ISSUE TITLE
Archive Board Confirmation Dialog UI

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#83]
We need a UI for when the user presses the archive board button

**Comment by nbot0902** [comment]
![1-6-2](https://user-images.githubusercontent.com/11695391/153997079-359bf3d2-3db1-4eae-8a9b-257b9e50e2ba.png)
![1-6-1](https://user-images.githubusercontent.com/11695391/153997089-c4506f27-6d5d-4de1-b87b-482931bb26a0.png)
