### ISSUE TITLE
Design UI for archived boards

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#84]
As a user, I want to see all the boards that I have archived and I want to be able to press a button to return the archived workspace board back to its workspace.

**Comment by nbot0902** [comment]
![1-12-1](https://user-images.githubusercontent.com/11695391/154184164-c9ece075-84c4-451d-99f0-5996daa59b9d.png)

**Comment by nbot0902** [comment]
![1-1](https://user-images.githubusercontent.com/11695391/154186234-ab3631be-a353-4f32-a516-7d13fd5d9519.png)

**Comment by nbot0902** [comment]
![1-2](https://user-images.githubusercontent.com/11695391/154186462-24608c89-acdb-49ee-97ea-a3785484ad2b.png)

**Comment by justuswilhelm** [comment]
Great!
