### ISSUE TITLE
Design UI for adding new workspace boards to workspace

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#85]

**Comment by nbot0902** [comment]
![Uploading スクリーンショット 2022-02-15 13.37.26.png…]()

**Comment by nbot0902** [comment]
<img width="761" alt="スクリーンショット 2022-02-15 13 41 39" src="https://user-images.githubusercontent.com/11695391/153993890-6c73e778-6a91-4da3-9ccb-225e15d12eaf.png">

**Comment by nbot0902** [comment]
![1-3-2](https://user-images.githubusercontent.com/11695391/154182409-5ff49cf3-e8c5-4457-9739-3559096d54c2.png)
