### ISSUE TITLE
Add save button to title edit field

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#88]
- [x] Task title
- [x] Workspace Board Section title
- [x] Workspace Board title
- [x] Workspace title (Should be renamed from Project name) https://www.figma.com/file/6QBQfUV5Z9jR14ZPlvNxNe/jwp-consulting?node-id=19%3A1581

**Comment by nbot0902** [comment]
I want to save by pressing the Enter key.

**Comment by nbot0902** [comment]
@justuswilhelm 
If there is no problem, please close it.

**Comment by justuswilhelm** [comment]
Not everyone understands how to save using the enter button. I want to make our application easy to understand.

**Comment by nbot0902** [comment]
It is assumed that you press the Enter key to remove the focus and return to the screen.

**Comment by justuswilhelm** [comment]
Not everyone understands that. A save button should be provided as a fallback.

**Comment by nbot0902** [comment]
![1-3-3](https://user-images.githubusercontent.com/11695391/154193051-ec055fa2-b8c9-4fd0-9199-a747b8fa294f.png)
![1-2-3](https://user-images.githubusercontent.com/11695391/154193055-2e6a3adb-4d83-4c98-abab-11c8b52947e2.png)
![1-10](https://user-images.githubusercontent.com/11695391/154193058-469c2a81-1de7-49bd-a34c-336fbf081dc6.png)
![1-2](https://user-images.githubusercontent.com/11695391/154193064-c0cd30f2-d6fa-4b4d-9c98-e260ae99b4b7.png)

**Comment by justuswilhelm** [comment]
Very good! Thank you :)
