### ISSUE TITLE
Add subtask creation UI

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#89]

**Comment by nbot0902** [comment]
![1-3](https://user-images.githubusercontent.com/11695391/154190371-b24756e3-cef7-4628-bfed-84ee4de551d7.png)
![1-4](https://user-images.githubusercontent.com/11695391/154190378-bf8e8751-c8ac-4268-947c-a1cbc14112f0.png)

**Comment by justuswilhelm** [comment]
Good!
