### ISSUE TITLE
Make profile picture upload more obvious

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-frontend#90]
When going to the profile settings, the user should be able to easily understand how to upload a new profile picture

**Comment by nbot0902** [comment]
<img width="697" alt="スクリーンショット 2022-02-16 12 56 14" src="https://user-images.githubusercontent.com/11695391/154193330-5e4d26d3-2674-45e2-97cb-7b2c31ebb05f.png">

**Comment by justuswilhelm** [comment]
Great, thanks!
